name: Portfolio Deployment

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: list repository files
      run: |
        echo "Listing file that present in the repository"
        ls -R ${{ github.workspace }} 

    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v4
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ap-south-1
    # - name: Verify AWS identity
    #   run: aws sts get-caller-identity

    # - name: Deploy static site to S3 bucket
    #   run: aws s3 sync . s3://niks-portfolios --delete

    - name: Print "Hello World !"
      run: echo "Hello World !"

    - name: print the current date
      run: echo "Current Date $(date +'%Y-%m-%dT%H:%M:%S')"

    - name: print event type
      run: echo "The event type ${{ github.event.type }}"
    
    # - name: print PR Number on pull
    #   if: ${{ github.event_name == 'pull_request' }}
    #   env:
    #     PR_NUMBER: ${{ github.event.pull_request.number }}
    #   run: echo "The PR Number is $PR_NUMBER"


    - name: print the current repository
      run: |
        echo "Repo: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Actor: ${{ github.actor }}"
